services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION}
    restart: unless-stopped
    container_name: cadvisor
    privileged: true
    devices:
      - "/dev/kmsg"
    labels:
      - traefik.enable=true
      - traefik.http.routers.cadvisor.rule=Host(`cadvisor-${DOCKER_REGION}.${DOCKER_INTERNAL_DOMAIN}`)
    ports:
      - 8080:8080
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"

networks:
  default:
    external: true
    name: backend-net

