services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
      - PORT=5055 #optional
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${DOCKER_DOMAIN}`)
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
    ports:
      - "5055:5055"
    volumes:
      - config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

networks:
  default:
    external: true
    name: backend-net

volumes:
  config:
