services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOCKER_INTERNAL_DOMAIN}`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    volumes:
      - ${DOCKER_VOLUMES}/radarr-config:/config
      - downloads:/downloads
      - media:/media

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    container_name: bazarr
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOCKER_INTERNAL_DOMAIN}`)
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    volumes:
      - ${DOCKER_VOLUMES}/bazarr-config:/config
      - media:/media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    container_name: prowlarr
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOCKER_INTERNAL_DOMAIN}`)
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    volumes:
      - ${DOCKER_VOLUMES}/prowlarr-config:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOCKER_INTERNAL_DOMAIN}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    volumes:
      - ${DOCKER_VOLUMES}/sonarr-config:/config
      - downloads:/downloads
      - media:/media

networks:
  default:
    external: true
    name: backend-net

volumes:
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.lan,nolock,soft,rw"
      device: ":/mnt/cosmere/qbittorrent"
  media:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.lan,nolock,soft,rw"
      device: ":/mnt/cosmere/jellyfin"

